# Generated by Django 3.0.6 on 2020-05-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('room_type', models.CharField(choices=[('Twin Room With Seaview', 'Twin Room With Seaview'), ('Deluxe Suite', 'Deluxe Suite'), ('Double Room', 'Double Room'), ('Single Room', 'Single Room')], max_length=100, null=True)),
                ('feedback_type', models.CharField(choices=[('Compliment', 'Compliment'), ('Complaint', 'Complaint'), ('Both', 'Both')], max_length=100, null=True)),
                ('service_type', models.CharField(choices=[('Food', 'Food'), ('Room', 'Room'), ('Spa', 'Spa'), ('Others', 'Others')], max_length=100, null=True)),
                ('feedback_description', models.TextField(max_length=200)),
            ],
        ),
    ]
