# Generated by Django 3.0.6 on 2020-05-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='room_number',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
