# Generated by Django 3.0.5 on 2020-05-28 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0005_auto_20200527_1333'),
        ('hotel_app', '0003_feedback_room_number'),
    ]

    operations = [
    ]
