# Generated by Django 3.0.5 on 2020-05-28 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0006_merge_20200528_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
