# Generated by Django 3.0.6 on 2020-05-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0006_auto_20200530_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='View_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_from', models.CharField(max_length=50)),
                ('Date_to', models.CharField(max_length=50)),
                ('adult', models.IntegerField(default=0)),
                ('children', models.IntegerField(default=0)),
                ('number_of_rooms', models.IntegerField(default=0)),
                ('rooms', models.CharField(max_length=50)),
            ],
        ),
    ]
