# Generated by Django 3.0.6 on 2020-05-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0007_view_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='view_room',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
