# Generated by Django 3.0.6 on 2020-06-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0011_auto_20200531_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='state',
        ),
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
