# Generated by Django 3.0.6 on 2020-06-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0012_auto_20200601_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.IntegerField(),
        ),
    ]
